server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranjithpn292/SB-PROJ-Config-Server
          clone-on-start: true